"""Ajustar nombres y relaciones

Revision ID: 3dbb19c5622a
Revises: 46cdef3f7c9d
Create Date: 2024-12-02 04:49:05.190889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbb19c5622a'
down_revision = '46cdef3f7c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.drop_column('coddepto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coddepto', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
