"""Actualizar modelos con nuevas relaciones

Revision ID: 7e6542fdf2da
Revises: aa1a534366a9
Create Date: 2024-12-03 11:50:00.028102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6542fdf2da'
down_revision = 'aa1a534366a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acceso', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.create_unique_constraint(None, ['rut'])

    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.drop_constraint('departamentos_rutarre_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'acceso', ['rutarre'], ['rut'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('departamentos_rutarre_fkey', 'arrendatarios', ['rutarre'], ['rutarre'])

    with op.batch_alter_table('acceso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    # ### end Alembic commands ###
