"""Agregar CalorCobrado a la tabla

Revision ID: aa1a534366a9
Revises: e2c1a6643145
Create Date: 2024-12-03 10:42:54.533744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1a534366a9'
down_revision = 'e2c1a6643145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuotasgc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ValorCobrado', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuotasgc', schema=None) as batch_op:
        batch_op.drop_column('ValorCobrado')

    # ### end Alembic commands ###
