"""Cambiar campo Estado de Boolean a String en Reclamo

Revision ID: e2c1a6643145
Revises: aea891c3650a
Create Date: 2024-12-02 13:11:27.834902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c1a6643145'
down_revision = 'aea891c3650a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
